# Generated by Django 5.0.6 on 2024-06-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='isCompleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
