# Generated by Django 5.0.6 on 2024-06-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskmodel_iscompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
