# Generated by Django 5.0.6 on 2024-06-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_taskmodel_iscompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='taskAssignDate',
            field=models.DateField(null=True),
        ),
    ]
