# Generated by Django 5.0.6 on 2024-06-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_categorymodel_delete_categormodel'),
        ('task', '0004_alter_taskmodel_taskassigndate'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='taskCategory',
            field=models.ManyToManyField(to='category.categorymodel'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='taskAssignDate',
            field=models.DateField(),
        ),
    ]
